package com.avernet.myworkoutapi.error;

public enum ErrorCodeEnum {
    UNKNOWN_MUSCLE,
    EMAIL_ALREADY_IN_USE,
    USER_NOT_FOUND,
    WORKOUT_NOT_FOUND,
    HISTORY_NOT_FOUND,
    EXERCISE_NOT_FOUND,
    INVALID_TOKEN,
    INVALID_USER,
    MUSCLE_GROUP_NOT_FOUND,
    MUSCLE_NOT_FOUND,
    INVALID_DATA,
    EXERCISE_NAME_ALREADY_EXIST,
    PASSWORD_NOT_MATCH,
    QUOTA_EXCEEDED,
    DOUBLE_MUSCLE_GROUP
}
