version: '3'
services:
  my-workout-app:
    image: alexv31/my-workout:app
    networks:
      - my-workout-network
    ports:
      - "3008:80"
      - "3009:443"

  my-workout-api:
    image: alexv31/my-workout:api
    depends_on:
      - my-workout-db
    environment:
      - spring.application.name=my-workout-api
      - spring.datasource.url=
      - spring.datasource.username=
      - spring.datasource.password=
      - spring.jpa.hibernate.ddl-auto=
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
      - spring.flyway.locations=classpath:db/migration
      - spring.flyway.baseline-on-migrate=
      - server.servlet.context-path=/api
      - allowed.origin=
      - security.jwt.secret-key=
      - security.jwt.expiration-time=
      - security.jwt.refresh.expiration-time=
      - logging.level.org.springframework.security=
      - server.port=80
      - server.address=
      - gemini.api.key=
    networks:
      - my-workout-network
    ports:
      - "4008:80"
      - "4009:443"

  my-workout-db:
    image: postgres:17
    restart: always
    networks:
      - my-workout-network
    environment:
      - POSTGRES_DB=my-workout-local
      - POSTGRES_USER=my-workout-dev
      - POSTGRES_PASSWORD=my-workout-dev
    ports:
      - "5008:5432"
      - "5009:443"

volumes:
  postgres_data:

networks:
  my-workout-network:
    driver: bridge
